---

all:
  # __________________________________________________________________________ #
  # all.children: this is one ansible way to create groups of hosts with YAML
  #               format, and one alternative to separate files on
  #               group_vars/groupname
  children:
    all_nodes:
      hosts:
       covid_ivanovsky:
       # covid_pasteur:
       # covid_mayer:
    all_mainservers:
      hosts:
      covid_ivanovsky:
      # covid_pasteur:
      # covid_mayer:

  # __________________________________________________________________________ #
  # all.hosts: this is one YAML alternative to separate files on
  #            host_vars/host_name. It's the place where we put variables very
  #            specific to a host that are not common to all (See: all.vars) or
  #            related to group (See; all.children).
  hosts:
    covid_ivanovsky:
      # IPv4: 167.86.127.225
      ansible_host: covid-ivanovsky.vps.etica.ai # aguia-pescadora-foxtrot.etica.ai
      ansible_python_interpreter: "/usr/bin/python3"

    # covid_mayer:
    #     # IPv4: 167.86.127.220
    #     ansible_host: covid-mayer.vps.etica.ai # aguia-pescadora-echo.etica.ai
    #     ansible_python_interpreter: "/usr/bin/python3"

    # Proxy server
    # covid_pasteur:
    #     # IPv4: XXX.XXX.XXX.XXX
    #     ansible_host: covid-pasteur.vps.etica.ai
    #     ansible_python_interpreter: "/usr/bin/python3"

  # __________________________________________________________________________ #
  # all.vars: This is where we specify variable common to all hosts and groups.
  #           Sometimes is possible to use variables, like
  #           app_domain: "hello-world.{{ ansible_default_ipv4.address }}.nip.io"
  vars: