---

all:
    children:
        all_nodes:
          hosts:
            c19cplp_foxtrot:
            # c19_proxy1:

    hosts:
        c19cplp_foxtrot:
        # IPv4: 167.86.127.225
        ansible_host: aguia-pescadora-foxtrot.etica.ai
        ansible_python_interpreter: "/usr/bin/python3"

        # covid19_proxy1:
        # # IPv4: xxx.xxx.xxx.xxx
        # ansible_host: aguia-pescadora-foxtrot.etica.ai
        # ansible_python_interpreter: "/usr/bin/python3"
