---

all:
    children:
        all_nodes:
          hosts:
            covid_ivanovsky:
            # covid_pasteur:
            # covid_mayer:

    hosts:
        covid_ivanovsky:
            # IPv4: 167.86.127.225
            ansible_host: covid-ivanovsky.vps.etica.ai # aguia-pescadora-foxtrot.etica.ai
            ansible_python_interpreter: "/usr/bin/python3"

        # covid_mayer:
        #     # IPv4: 167.86.127.220
        #     ansible_host: covid-mayer.vps.etica.ai # aguia-pescadora-echo.etica.ai
        #     ansible_python_interpreter: "/usr/bin/python3"

        # Proxy server
        # covid_pasteur:
        #     # IPv4: XXX.XXX.XXX.XXX
        #     ansible_host: covid-pasteur.vps.etica.ai
        #     ansible_python_interpreter: "/usr/bin/python3"

