---

all:
  # __________________________________________________________________________ #
  # all.children: this is one ansible way to create groups of hosts with YAML
  #               format, and one alternative to separate files on
  #               group_vars/groupname
  children:
    all_nodes:
      hosts:
        oswaldo_cruz_homolog:
    all_dbservers:
      hosts:
        oswaldo_cruz_homolog:

  # __________________________________________________________________________ #
  # all.hosts: this is one YAML alternative to separate files on
  #            host_vars/host_name. It's the place where we put variables very
  #            specific to a host that are not common to all (See: all.vars) or
  #            related to group (See; all.children).
  hosts:
    oswaldo_cruz:
      # IPv4: 167.86.127.225
      oswaldo_cruz_homolog: oswaldo-cruz.hom.vps.etica.ai
      ansible_python_interpreter: "/usr/bin/python3"

  # __________________________________________________________________________ #
  # all.vars: This is where we specify variable common to all hosts and groups.
  #           Sometimes is possible to use variables, like
  #           app_domain: "hello-world.{{ ansible_default_ipv4.address }}.nip.io"
  vars: