---
# FILE:            apps-userland.yml
# LICENSE:         Public Domain
# DESCRIPTION:     Aplica ações que são meio termo entre infraestrutura e os
#                  apps que rodam nela.
#                    - Gerencia usuarios, grupos e permissoes
#                    - gerencia pastas
#                    - Instala PHP, Composer, etc
# USAGE:
# To run this playbook alone, use:
#     ansible-playbook -i inventories/cssg-prod/hosts.yml --vault-password-file .valt/pass playbooks/apps-userland.yml --diff

- name: "apps-userland.yml: Aplica ações que são meio termo entre infraestrutura e os apps que rodam nela (usuarios, grupos, pastas, PHP, Composer...)"
  hosts: all
  remote_user: root
  gather_facts: true
  debugger: on_failed
  vars:

    a2s_users_default:
      shell: /bin/bash

    a2s_users:
      - name: fititnt
        groups: ["wheel"]
        comment: "Emerson Rocha"
        authorized_keys:
          - key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkyJFXqlSGsPijXGSWwaizYLWrwpfxHUA6VkwuLmitudmLyvMHXS67IOZa25LHXVGcGJWD9f3xJPPlkGVNb+Oo5fL2gHFzQffglgZySQl0ixlf2UN6xmfgTk2HuCyXKO3zez8MWpzMukurZg4mUJtLBFExLy6Q6XDUW7mRn97KYND7MRFwXx76kuzVYGHxIEBbqT4gqg5bQzPFGQnUnlhXfE7lkRjpzD5P8bisicyOfZdyjxAtNvsSl+/9fvvBzcMAz8v/J8GerBKuXs2/odFewovkKBrDV2Vyt4phW7hx8G+/B7D/KIUOAEyRH5Z98l6UT9DyOp+K5VDQ+ciF140grddkSEznTdbQh1Te3tyJNhQo/ujgpqYVhQC2QGeRbLWQsoQS00t8xxNx5483We97Ods8FKNaBVlWwIqdr/s2JxCsPbLZ/Zjs4pM2Q/53rs/50HfBDe0oEbXRGkXxRtGMwNQQ//yaeuIDkzdwgKAfprlhZggCmtbiju3upsx1bjJQ79Qr8dTOGlG9GTxC4HM0MUr7W9QLcDSb831T/8a950wwleKnbuNe4p+cjnE7zqpQIj0JBrhWR34Rp7g2VYmt2I5kEGzIFocdS61vKaqiA+17dzcr2P/9XuhaWWp+6szJ3otGKe8v3P6yxxiJnvhN82w0AZhH2I/mH4042LYEJw== rocha@ieee.org"

      - name: igoralves1
        groups: ["wheel"]
        comment: "Igor Alves"
        authorized_keys:
          - key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIgb8dBQaQhpBEH2x6S6mgME+2gKQIspgn+qfm5ZFXhedkqWraIoV+C8HAAVh8dWZW/j/rTcmEXRr7jiIHKPu8lXqzjmC1jtj9tTg+SdxHQ/kHEhfItU9F0fIKTBiST0qZ3iWZR0lzGW+tXMuXBiwUxGQyjgz1H1yNLUzYqOoSJlBfW3DpmpK+D9RbcFFr8Asazz+1+otH0DV/92NOZ8hYDFjnHIP+uS8jAXiG8PKXIAnFr/+9+umlmSAYp65Ems/vZBO9yRRRfJ6iBI+ifL2Xw7SfufVb09zjpl0xi5xfutk05fiiYn52F2sYzKEYH5JDfproTKMduCiRZ0s4nayh igoralves1-key1"
          - key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCQw2LZio+bPoQxWmcUMAfMiIaIvnIiajdLIwgggT/FHyspJaAWijXB5xYgx9TBjj2MLzYSrbVSB/LWTHi4GEmPyW/IqcrgGNdZKqaNtd/Zr0Awu02+UatGDJOTr+pu1f9TcKrOxMpGMp5UbQuQa7xZwqe8vBzI4LOaoxIBWhzqWPNtXA6q+f4Hap7NYBtRAmtuoYXn/1QnfkgTbjQYqznpqnYvu0scJPXbPY6cHH11ieGFXYf0uS956IcPUtDIv92ofaODjCKhqr1zJTkJS3KK5WF/9RN8n6ZcX3QypVXNRLPhCIEVjsyBeFm+GVdjB//EaS2eJ+nIYmNnuhM202ub igoralves1-key2"

  roles:
    - role: fititnt.syntactic_sugar
      # vars:
      #   # a2s_only_apis:
      #   #   - a2s_rclone
      #   # #   - a2s_mysql_users
      #   a2s_only_apis_groups:
      #     # - inexistente
      #     - packaging-os
      #     - system
      #     - files
      #     - packaging-languages
      #     - a2s-extra # Adminer
      #     # - database
      #     #- system
      #     #- files
  # handlers:
  #   - name: "reload php7.4-fpm"
  #     service:
  #       name: php7.4-fpm
  #       state: reloaded
  #     listen: "a2s-template-templates changed"


# Debuguer
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_debugger.html#using-the-debugger-keyword
# p result._result
# p task.args