---
# FILE:            infra-passwordless-wheel.yml
# LICENSE:         Public Domain
# DESCRIPTION:
#
# To run this playbook alone, use:
#     ansible-playbook -i hosts.yml playbooks/infra-passwordless-wheel.yml

- name: "infra-passwordless-wheel.yml: Add/Edit group wheel be able to passwordless sudo"
  hosts: all
  remote_user: root
  gather_facts: true
  debugger: on_failed
  tasks:
    - name: "Create group wheel if does not exist"
      group:
        name: wheel
        state: present

    - name: "Edit /etc/sudoers, group wheel to be able to sudo without password"
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
        backup: yes

# Debuguer
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_debugger.html#using-the-debugger-keyword
# p result._result
# p task.args